### ISSUE TITLE
Latest bits are not in dist folder nor jsdelivr

### ISSUE THREAD

**Issue by shapeh** [haacked/aspnet-client-validation#102]
This commit (https://github.com/haacked/aspnet-client-validation/commit/692acb52a4e0c5853d3de5d86f240a93cd397b1a) is not in the /dist folder - see here https://github.com/haacked/aspnet-client-validation/blob/5008fe31af9c0e78d655d76c64e98ac21e2805d5/dist/aspnet-validation.js#L416C16-L416C46

Perhaps build was not run after merge?

In turn, bits on [jsdelivr](https://www.jsdelivr.com/package/npm/aspnet-client-validation) are not updated as well.

Updating the bits, fixes issue with `PageRemote/Remote` (https://github.com/haacked/aspnet-client-validation/issues/101).

@haacked please help :)

**Comment by haacked** [comment]
I just published a new release! Please try it out and let me know if it addressed the issues you mentioned.
