### ISSUE TITLE
The isValid method throws if the form does not contain any validation attributes

### ISSUE THREAD

**Issue by derTuca** [haacked/aspnet-client-validation#104]
Hi,

I am using a function that calls `ValidationService.isValid` on every page on my site, but some pages do not have any validated fields. When called on a form with no fields that have validation, I would expect the return value to be `true`. Instead, the method throws on this line: ` var invalidFormInputUIDs = formInputUIDs.filter(...)` with the error `formInputUIDs is undefined`.

**Comment by dahlbyk** [comment]
You're absolutely right. PR incoming.

**Comment by dahlbyk** [comment]
@derTuca I'm pretty confident, but feel free to give https://github.com/haacked/aspnet-client-validation/pull/105 a try.

**Comment by dahlbyk** [comment]
Fix shipped in https://www.npmjs.com/package/aspnet-client-validation/v/0.9.6, please let us know if you still see an issue.
