### ISSUE TITLE
Sample project in npm distribution?

### ISSUE THREAD

**Issue by hangy** [haacked/aspnet-client-validation#124]
When upgrading [from ^0.8.1 to ^0.11.0](https://github.com/haacked/aspnet-client-validation/compare/v0.8.1...v0.11.0), we noticed that the new sample project is part of the package that's [published in npm](https://www.npmjs.com/package/aspnet-client-validation/v/0.11.0?activeTab=code). For some reason `dotnet publish` also tries to build `node_modules\aspnet-client-validation\DemoWeb.csproj`.

This shouldn't be an issue of this library, but I was wondering if it's intentional that this demo project's C# source is being published in the npm package.

**Comment by haacked** [comment]
That is not intentional. I'll take a look.

**Comment by hangy** [comment]
Awesome, thank you @haacked! 😄
