### ISSUE TITLE
Missing Code From Release

### ISSUE THREAD

**Issue by justin-nevitech** [haacked/aspnet-client-validation#13]
Several functions are missing from the release zip file when compared to the code from the repo.  For example, I can see the following functions missing when comparing the code from the aspnet-validation.js to the same file in the 0.5.1 release zip.

focusFirstInvalid
isValid
isFieldValid

You can see the differences if you compare the files.

**Comment by haacked** [comment]
Check out the latest 0.5.4 release. Is it still an issue?

**Comment by haacked** [comment]
Ok, I think I know what happened and I created a GitHub workflow so it doesn't happen again.
