### ISSUE TITLE
How to validate hidden fields?

### ISSUE THREAD

**Issue by dotnetshadow** [haacked/aspnet-client-validation#16]
Hi there,

I know there was a change made to ignore hidden fields to be validated. What about if you require the hidden fields to be validated such as in the case of kendo ui
http://www.macaalay.com/2014/02/15/enabling-asp-net-mvc-client-validation-for-kendo-ui-components/

Would be possible to include a something to enable this?

**Comment by haacked** [comment]
I'd accept a pull request to enable it.

**Comment by dotnetshadow** [comment]
Updated the pull request to fix the typo

**Comment by haacked** [comment]
This was done in #20. Thanks!
