### ISSUE TITLE
[Docs] Changing css class names

### ISSUE THREAD

**Issue by lonix1** [haacked/aspnet-client-validation#34]
Apparently [it's possible](https://github.com/haacked/aspnet-client-validation/issues/25) to change the default css class names, so we could use this library with bootstrap (for example).

But I can't find mention in the README, and haven't been able to figure it out.

Does someone know how to use the feature?

**Comment by haacked** [comment]
Looking at the code, it looks like you set these properties on `ValidationService`:

* `ValidationInputCssClassName` - Override CSS class name for an input that has a validation error. Default: 'input-validation-error'
* `ValidationInputValidCssClassName` - Override CSS class name for a valid input. Default: 'input-validation-valid'
* `ValidationMessageCssClassName` - Override CSS class name for field validation error. Default: 'field-validation-error'
* `ValidationMessageValidCssClassName` - Override CSS class name for valid field validation. Default: 'field-validation-valid'

For example, it might look like the following if you're using TypeScript or ES modules:

```js
import 'ts-polyfill';
import { ValidationService } from 'aspnet-client-validation';

let v = new ValidationService();
v.ValidationInputCssClassName = 'my-input-error-class';
v.ValidationMessageCssClassName = 'my-field-error-class';
v.bootstrap();
```

Try it out and let me know if it works. I'll try it when I'm back home.
