### ISSUE TITLE
Validating list of radio buttons not working

### ISSUE THREAD

**Issue by andreasnylin** [haacked/aspnet-client-validation#36]
I really like this library. I want to get rid of jQuery from our website.
However I'm having issues validating groups of radio buttons with this library. I have a list of `<input type=radio asp-for="@MyModel">`. The model has `[Required]`-attribute. By default .net will render `data-val` and `data-val-required` attribute for the first input. But when I post the form the radio buttons are not validated. The form is sent even if no radio button option is selected. If i use `<input type=text>` the validation works fine. 

This is something i think works out of the box with jquery.validate.unobtrusive.

Another issue is if I'm using a Validation summary `@Html.ValidationSummary()` and the form is validated on the client it will remove the header rendered by `@Html.ValidationSummary()`. It seems that the script replaces the content of the validation summary element instead of just updating the content of the ul-list.

**Comment by haacked** [comment]
Do you have a repro you can provide? Perhaps a model and some `.cshtml` markup that demonstrates the problem?

**Comment by andreasnylin** [comment]
You can reproduce the problem with this simple HTML-code:
https://gist.github.com/andreasnylin/eea30c52e054da63c022884e580e8ee0
