### ISSUE TITLE
Validation breaks the formaction attribute

### ISSUE THREAD

**Issue by 7702244** [haacked/aspnet-client-validation#39]
Suppose there is the following form:

```
<form action="/action_page.php">
  First name: <input type="text" name="fname"><br>
  Last name: <input type="text" name="lname"><br>
  <button type="submit">Submit</button><br>
  <button type="submit" formaction="/action_page2.php">Submit to another page</button>
  <button type="submit" name="param" value="val">Submit with param</button>
</form>
```

When using aspnet-client-validation, the form does not take into account the `formaction` attribute and the key/value passed to submit (if it was clicked). The only working solution is to add `formnovalidate` attribute to buttons.
```
<form action="/action_page.php">
  First name: <input type="text" name="fname"><br>
  Last name: <input type="text" name="lname"><br>
  <button type="submit">Submit</button><br>
  <button type="submit" formnovalidate="formnovalidate" formaction="/action_page2.php">Submit to another page</button>
  <button type="submit" formnovalidate="formnovalidate" name="param" value="val">Submit with param</button>
</form>
```

**Comment by haacked** [comment]
> When using aspnet-client-validation, the form does not take into account the `formaction` attribute and the key/value passed to submit (if it was clicked).

What is the behavior you observed and what is the behavior you expect?

**Comment by Forthoney** [comment]
Just hijacking the thread to report the same issue where the form action is ignored. I also wanted to add more detail to what is happening vs what should happen
The context in which I noticed this is using `asp-page-handler` on my submit button like so:
`<input type="submit" asp-page-handler="example" />`
I expect to be routed to something like `destinationPage/5?handler=example`. 
But using the validation routes me to `destinationPage/5`, as confirmed by loggingin the console.

Here's the exact discrepancy I am encountering.
![image](https://github.com/haacked/aspnet-client-validation/assets/85617794/a736674c-bc97-47f1-ba46-b543ec04ac17)
![image](https://github.com/haacked/aspnet-client-validation/assets/85617794/3808c9f7-ca46-4d1f-8e68-2e3cd4e8b6af)

Considering `asp-page-handler` is a built in component to Razor pages and needing multiple POST methods is a fairly common occurance, I think this is a pretty critical bug. I haven't looked too deeply into the codebase, so I can't offer much insight into where the bug may be coming from, but if you have some ideas on where the problem may lie, I can try taking this on

**Comment by haacked** [comment]
I was not able to reproduce this. I added a demo page for formaction here: https://github.com/haacked/aspnet-client-validation/pull/84

Here's the razor code:

```razor
@page
@model DemoWeb.Pages.Demos.FormAction


@{
    Layout = "Shared/_Layout";
}

<partial name="Shared/_StatusMessage" model="Model.StatusMessage"/>

<form method="post">
    <input type="submit" value="Submit" asp-page-handler="Submit" />
    <input type="submit" value="Save" asp-page-handler="Save"/>
</form>
```

Here's the code behind:

```csharp
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DemoWeb.Pages.Demos;

public class FormAction : PageModel
{
    [TempData]
    public string? StatusMessage { get; set; }


    public IActionResult OnPostSubmitAsync()
    {
        StatusMessage = "Submit button clicked";

        return RedirectToPage();
    }

    public IActionResult OnPostSave()
    {
        StatusMessage = "Save button clicked";

        return RedirectToPage();
    }
}
```

And it works fine as the screenshots show.

<img width="478" alt="Screenshot 2023-12-12 at 12 10 25 PM" src="https://github.com/haacked/aspnet-client-validation/assets/19977/dd152ade-eb9e-494b-b9be-c560803e724e">

<img width="474" alt="Screenshot 2023-12-12 at 12 10 32 PM" src="https://github.com/haacked/aspnet-client-validation/assets/19977/66a72340-fbee-4bf9-8504-cc3028b15acb">

**Comment by JLS-Envision** [comment]
@haacked I have been running into this issue and can reproduce it. It seems you have to have some form fields in addition to the buttons on the form to trigger the issue. I have been having some trouble getting the source to build locally and cannot get a proper pull request together right now, but if you make some minor modifications to the FormAction page mentioned above you should be able to reproduce the problem.

FormAction.cshtml.cs becomes:

```
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace DemoWeb.Pages.Demos;

public class FormAction : PageModel
{
    [TempData]
    public string? StatusMessage { get; set; }

    [BindProperty]
    public InputModel Input { get; set; }

    public class InputModel
    {
        [Display(Name = "Name")]
        [Required, StringLength(50)]
        public string? Name { get; set; }
    }

    public IActionResult OnPostSubmitAsync()
    {
        StatusMessage = "Submit button clicked";

        return RedirectToPage();
    }

    public IActionResult OnPostSave()
    {
        StatusMessage = "Save button clicked";

        return RedirectToPage();
    }
}
```

FormAction.cshtml becomes:

```
@page
@model DemoWeb.Pages.Demos.FormAction

@{
    Layout = "Shared/_Layout";
}

<partial name="Shared/_StatusMessage" model="Model.StatusMessage"/>

<form method="post">
    <div asp-validation-summary="All">The following problems occurred when submitting the form:</div>
    <div>
        <label asp-for="Input.Name"></label>
        <input asp-for="Input.Name" />
        <span asp-validation-for="Input.Name" ></span>
    </div>
    <input type="submit" value="Submit" asp-page-handler="Submit" />
    <input type="submit" value="Save" asp-page-handler="Save"/>
</form>
```

Hope this helps.

**Comment by haacked** [comment]
> I have been having some trouble getting the source to build locally

What issues? Mind filing another issue for that?

**Comment by haacked** [comment]
> Hope this helps.

That helped a lot! I can confirm the issue.

**Comment by JLS-Envision** [comment]
> > I have been having some trouble getting the source to build locally
> 
> What issues? Mind filing another issue for that?

The problems I had were around getting NPM to behave on my machine, so I don't think it is an issue specifically with this project. I had planned on trying to work through it to sort the problem out but I keep getting sidetracked. Will definitely file an issue if I find something and think it is helpful though.
