### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by VaclavElias** [haacked/aspnet-client-validation#4]
This and source fork doesn't say **clearly** one importing thing. It would be good to mention in your intro.

Can I just replace jquery.validate.min.js + jquery.validate.unobtrusive.min.js with this library and the validation would just work same way in ASP.NET Core application?

Meaning that this library is actually compatible and takes over or you have to code your own validation regardless?

Thank you.

**Comment by haacked** [comment]
That's a good suggestion. I clarified the README. You can see the change in d35b897.

**Comment by VaclavElias** [comment]
Thank you @haacked. That is now very clear :)

Now I have got a question. What are the cons to make it auto initialized like the original jquery library. I think obviously it should be same customizable as it is but if there aren't any cons then maybe it would be nice doing it that way?

One of the reasons is that I don't want to write any JavaScript. I just want to plug in and use it. Obviously even current way is ok :)

And thanks for taking over this plug in.

**Comment by haacked** [comment]
Let me think about this a bit and get back to you.

**Comment by VaclavElias** [comment]
Sure, I myself have no idea. Not that super experienced with JavaScript. Maybe we should create a new issue and wait for more feedback from others. Or gentlemen from ASP.NET Core could give some input as they are also considering or thinking to move away from jquery https://github.com/dotnet/aspnetcore/issues/8573

**Comment by haacked** [comment]
Looks like there's another library that's a drop-in replacement. https://github.com/NonFactors/Wellidate

The main concern I have is in situations where you need to gain access to the validation library in your code so you can trigger validation in response to other events. I could easily add another simple script that bootstraps this script. That would give you the benefit of both worlds. It would "just work" but at the same time, you could `import {ValidationService} from "aspnet-client-validation";` when you needed access to the library.

**Comment by VaclavElias** [comment]
Sounds good.

I also use TypeScript so definitelly there should be an access as you are saying to trigger validation in response on other events. I guess you could also do this in jquery valiadtion to take over if you needed doing anything more?

I saw Wellidate but there isn't too much written about it and your library was promoted on ASP.NET Community Standup :) Also Wellidate seems must be initialized as well. 

I guess that would be a community to decide which one seems more workable for them.

I will try to play with your library on one of my project so hopefully can give you more input.
