### ISSUE TITLE
Validation on submit not work

### ISSUE THREAD

**Issue by rasoulia** [haacked/aspnet-client-validation#49]
Hi. Thanks for creating this JavaScript library. So we can drop jquery.
There are 2 problems. (And sorry for my English)
1. When submit form without writing anything it's not show validation message.
2. When using validation with JavaScript code it's always return false.

**Comment by girishnuli** [comment]
Same experience here. Jquery unobtrusive validation works fine, but when replaced it with this, validation is always returning false even if all the form fields are filled in correctly. Tested it by initializing in global script as well as in a page specific form submit event handler.

**Comment by haacked** [comment]
Can you provide a small repro?

**Comment by rasoulia** [comment]
I don't know what repro mean (not good at english) but if you mean how i created and use this script. I do the following steps 
1. Create form with form tag helper and asp-validation-for.
2. Add script with local file and initialize it.
3. Open page and then press submit button.
4. There is no message of validation.
5. But if i use jQuery validation it's show all of required message.

And for form validation with JavaScript without using submit button always return false it's not matter form is valid or not.

**Comment by haacked** [comment]
Can you send me the code you wrote?

**Comment by rasoulia** [comment]
```
<form id="FrmTest">
    <label>For Test</label>
    <input type="text" aso-for="Test">
    <span asp-validation-for="TestInput"></span> 
    <input type="submit" />@*if i press submit button without writing anything it's not show anything unless 

                            i type somthing in field and then press submit. validation on change work fine.*@
</form>

<script>
    var v = new aspnetValidation.ValidationService();
    v.bootstrap();


    const frm = document.getElementById("FrmTest");
    const isValidForm = v.validateForm(document.getElementById(frm)); // this always return false.
</script>
```

**Comment by haacked** [comment]
Can you show me the code behind?

Also, I see a typo in the code sample:

I think `<input type="text" aso-for="Test">`  should be `<input type="text" asp-for="TestInput">`

**Comment by rasoulia** [comment]
Yes you right thanks. I just do it that sample in vs code. I forogt to double check it.
Code behind? What you mean? Back end in c#?
If you mean back end i check that with Model.IsValidSate (if i remember correctly) and then if is false return model to view.

**Comment by haacked** [comment]
Yes, I need to see the C# code so I can try to reproduce the issue.

**Comment by rasoulia** [comment]
The only code i write is `ModelState.IsValidand` if that is false return model to view `return View(myModel)`

**Comment by haacked** [comment]
What does the model look like. I can’t help you if you don’t provide the backend code.

**Comment by rasoulia** [comment]
Like this
```
[Required("error message")]
[MinLenght(20,"error message")]
[MaxLenght(100,"error message")]
Public string test1 {get; set;}

[Required("error message")]
[Range(20,30,"error message")]
Public int test2 {get; set;}
```

**Comment by haacked** [comment]
Hmm, I tested it and it works fine. Here's some sample code:

__SimpleValidatioDemo.cshtml__

```cshtml
@page
@model DemoWeb.Pages.Demos.SimpleValidationDemo

<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"]</title>
    <title>ASP.NET Client Validation Demo Page</title>
    <link rel="stylesheet" href="/dist/aspnet-validation.css" />
</head>
<body>
    <form method="post">
        <label asp-for="Test1"></label>
        <input type="text" asp-for="Test1" />
        <span asp-validation-for="Test1"></span>
        <input type="submit" />
    </form>

    <script src="/dist/aspnet-validation.js"></script>
    <script>
        const service = new aspnetValidation.ValidationService(console);
        service.bootstrap();
    </script>
</body>
</html>
```

And here's the C# code.

__SimpleValidationDemo.cshtml.cs__

```csharp
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DemoWeb.Pages.Demos;

public class SimpleValidationDemo : PageModel
{
    [Required]
    [MinLength(20)]
    [MaxLength(100)]
    [BindProperty]
    public string? Test1 {get; set;}

    public void OnGet()
    {

    }
}
```

When you hit the submit button, validation occurs. Make sure you reference both the script `aspnet-validation.js` and the css file `aspnet-validation.css`.

**Comment by rasoulia** [comment]
Like this
```
[Required("error message")]
[MinLenght(20,"error message")]
[MaxLenght(100,"error message")]
Public string test1 {get; set;}

[Required("error message")]
[Range(20,30,"error message")]
Public int test2 {get; set;}
```

What about the second part of my problem?
