### ISSUE TITLE
Missing key value pairs within FormCollection

### ISSUE THREAD

**Issue by m3gawatt** [haacked/aspnet-client-validation#54]
Hello 👋

I have recently been attempting to transition away from jQuery and came across your solution as a replacement for validation.  However, I have encountered an issue related to the posting back of key-value pairs as part of the FormCollection.

Interestingly, this issue seems to be browser specific. Everything operates as expected when using Safari, but the values do not appear to be included in the FormCollection when the same operation is performed in Chrome.

Let's consider a basic form that includes a few buttons as an example:

```
<form asp-controller="" asp-action="" method="post">
    <input asp-for=”FirstName”>
    <input asp-for=”LastName”>
    <button name=”button” value=”button1” type=”submit”>Button One</button>
    <button name=”button” value=”button2” type=”submit”>Button Two</button>
<form>
```

In this case, the 'FirstName' and 'LastName' fields get posted back as part of my model correctly, but the button and its value don't appear within the FormCollection.

As I said above, what's unusual is that this functions correctly in Safari, but not in Chrome.

If I comment out aspnet-client-validation script, the key and value do become part of the FormCollection for both browsers.

Am I missing something or is there a misstep in my process? I would greatly appreciate any pointers.

Thank you

**Comment by haacked** [comment]
Are you using the latest version? I recently fixed a bug related to this.

**Comment by m3gawatt** [comment]
Ah, sorry, you are correct.  I was using v0.8.11, upgrading to v0.8.12 solved the issue.

Many thanks for your help.  Have a great day!
