### ISSUE TITLE
Form e.preventDefault() broken in Firefox (0.8.3-0.8.13)

### ISSUE THREAD

**Issue by dotnetshadow** [haacked/aspnet-client-validation#61]
Hi there,

It seems any code such as the following in Firefox breaks.
Chrome / Edge seem ok, but Firefox doesn't work

`document.getElementById('my-form').addEventListener('submit', function (e) {        
        e.preventDefault();        
        alert('This doesn't get called because the page navigates away');
});
`
The page just navigates away without being stopped

I tried various versions of the library and v0.8.1 is the last working version 
**0.8.3-0.8.13 BROKEN**

@dahlbyk I noticed you made some changes during 0.8.3 release anything you can think of that would stop it form working in Firefox?

I suspect an issue with this part of the code
https://github.com/haacked/aspnet-client-validation/compare/v0.8.1...v0.8.3#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R728
       
![image](https://github.com/haacked/aspnet-client-validation/assets/296247/a9a3f0a4-8bf0-464d-b05e-26042d9e9c9f)

Any help would be much appreciated

**Comment by dahlbyk** [comment]
> @dahlbyk I noticed you made some changes during 0.8.3 release anything you can think of that would stop it form working in Firefox?

Apparently https://github.com/haacked/aspnet-client-validation/pull/33 just doesn't work on Firefox. Here's a minimal repro and a proposed fix: https://codepen.io/dahlbyk/full/oNQQoMq.

![image](https://github.com/haacked/aspnet-client-validation/assets/133987/b631ab06-71e6-458f-ab4e-2e3c0b03da82)

In short, Firefox isn't firing `submit` listeners for the redispatch here:
https://github.com/haacked/aspnet-client-validation/blob/f09bb578574c129b07e06e4781fc47c0052314d3/src/index.ts#L718-L720

Using `setTimeout(fn, 0)` seems to allow the original `submit` handler to finish before dispatching at the next opportunity.

If the Pen seems to work for you I'll submit a PR.

**Comment by dahlbyk** [comment]
> I'll submit a PR.

Give #62 a try?

**Comment by dotnetshadow** [comment]
Thank you so much for fixing it, works great :)
