### ISSUE TITLE
google recaptcha client side validation

### ISSUE THREAD

**Issue by giannik** [haacked/aspnet-client-validation#69]
Is it possible to validate google recaptcha on the form using the library before it is submitted to server by including this code to be executed client side ?

https://html.form.guide/snippets/google-recaptcha-javascript-validation/

**Comment by dahlbyk** [comment]
It seems like you should be able to implement reCaptcha as a [custom validation](https://github.com/haacked/aspnet-client-validation#adding-custom-validation), but I don't think we'd consider including that in the project.
