### ISSUE TITLE
isFieldValid not working as expected if prevalidate is false

### ISSUE THREAD

**Issue by Maverik** [haacked/aspnet-client-validation#76]
Hi there,

First of all, thank you for taking on the maintenance role of the library after Ryan. I've just started using the library so if I'm doing something wrong, please point me in the right direction.

Otherwise I've created a [codepen repo](https://codepen.io/Maverik/pen/vYvMavr) with the problem and this is essentially the same problem as #28 I believe.

When I try to validate a specific field **with prevalidate set to false** in order to trigger an API call, the callback is never triggered and the result of isFieldValid appears to lag behind by one call.

i.e. if the last 7 results were false:
- you'll get true on first call (this is coming from default state of control while its in pristine state)
- you'll get false up-to the 8th call (1+7)
- true on the 9th call (1+8 even though the field was valid on the 8th call).
- lets say now the input was actually invalid on the 9th call, it'll take the 10th call to actually get that result.
 
I hope you can see now what I mean by "lagging behind by one call".

The behaviour only happens with pre-validate set to false as far as I can tell and behaves as expected when working with the entire form. Of course, that leaves a pretty bad impression when the entire form says its required, even though the user hasn't even gotten to rest of the form yet.

**Comment by dahlbyk** [comment]
Calling `isFieldValid()` with `prevalidate: false` always checks the latest cached validation result, instead of validating again before returning. So what you're seeing is what I would expect.

I'm not sure if we have a way to trigger validations only for a specific field.

**Comment by Maverik** [comment]
Thank you for the clarification there. It would be worth documenting the behaviour in the readme then perhaps as you'll likely get new users asking this same question anyway.

My JS/TS foo is much weaker than my C# but in the event, there was some interest from my side in possibly doing a PR for adding the functionality to bypass cache for validation optionally, would that be something meaningful for the library to have?

**Comment by dahlbyk** [comment]
Honestly the behavior of validating the *whole* form when asking if a single field is valid feels like a bug to me. We don't currently have a way to run validators for a single field, but that's not hard to add.

That would be a breaking change, though. Method was introduced in #8. Thoughts, @haacked?

**Comment by haacked** [comment]
I think we should probably add a method to `validateFormField(element)`

I wonder if it validates the whole form just in case there are dependencies. For example, if an element is only required if another field is valid or something like that. I’m AFK so I can’t look.

**Comment by dahlbyk** [comment]
@Maverik can you give this PR a try? https://github.com/haacked/aspnet-client-validation/pull/77

> I think we should probably add a method to `validateFormField(element)`

I like this as a counterpart to `validateForm`. I called it `validateField()`, since we don't use `FormField` anywhere.

> I wonder if it validates the whole form just in case there are dependencies. For example, if an element is only required if another field is valid or something like that.

Validators don't have access to the validation state of other inputs, so dependencies would be on _values_ of other inputs.

**Comment by dahlbyk** [comment]
> I find the `isFieldValid` to be still confusing (although I understand its behaviour now and its working as intended). I'm only unsure if `isFieldValid` should be reflecting the callback changes as reflected in `validateField`.

Sorry, I'm not sure what you mean by this? Are you referring to a mismatch between the return value and the value passed to the callback?

**Comment by Maverik** [comment]
Indeed. From my testing, `isFieldValid` still doesn't perform the callback (which validateField does as expected) as I'd expect it to & the result is still coming back as the cached result from last call I think. Here's a screenshot of what I mean (I'm attaching the screenshot for both prevalidate cases):

![image](https://github.com/haacked/aspnet-client-validation/assets/808099/eb6938c9-316d-4527-b026-6a451731d5e3)
![image](https://github.com/haacked/aspnet-client-validation/assets/808099/c93a7e43-1b29-4567-af67-6ca2d3978ace)

**Comment by dahlbyk** [comment]
A ha! I think you're hitting the debounce. If I comment out the `validateField()` then I see the `isFieldValid` callback result.
![image](https://github.com/haacked/aspnet-client-validation/assets/133987/c397c37c-fc1a-47ed-badb-7c522853205a)

**Comment by Maverik** [comment]
Thank you for figuring that out. I guess this sorts my use-case out. I might have to come back later, when I circle back to that story I was working on but for now, I think this covers all the bases and I can configure the debounce if i need to.
