### ISSUE TITLE
razor pageremote type=post

### ISSUE THREAD

**Issue by Wendy-Brooks** [haacked/aspnet-client-validation#80]
In this.remote = function:

return new Promise(function (ok, reject)
{
var request = new XMLHttpRequest();
if (params.type === 'post') | not 'Post'. better yet: params.type.tolowercase

**Comment by dahlbyk** [comment]
Here:
https://github.com/haacked/aspnet-client-validation/blob/4956e54606903351c9b9cc38a86a941aae6b1282/src/index.ts#L366-L369

Agree that a case-insensitive match would be preferred.
