### ISSUE TITLE
[Q] Reparse form without using `watch:true` MutationObserver

### ISSUE THREAD

**Issue by lonix1** [haacked/aspnet-client-validation#87]
The [docs show](https://github.com/haacked/aspnet-client-validation#monitoring-the-dom-for-changes) how to validate dynamically-modified forms with a MutationObserver via `v.bootstrap({ watch: true })`.

But that is a little heavy when I know exactly when and how new items are added to the form.

I want to replace jquery-validate where that is done by reparsing the form. Just out of interest, it's done like this:
```js
$(form).removeData("validator").removeData("unobtrusiveValidation");
$.validator.unobtrusive.parse(form);
```
I'm sure this library already has this built-in, but it doesn't seem to be documented.

Does someone know how to do this?

Thanks!

**Comment by dahlbyk** [comment]
> If this has unintended consequences, please let me know? ...e.g. will it track existing fields twice?

It shouldn't. Please let us know if you find that it does. 😁
