### ISSUE TITLE
Should not validate disabled fields

### ISSUE THREAD

**Issue by lonix1** [haacked/aspnet-client-validation#90]
The jQuery Validate plugin does not validate fields with the `disabled` attribute. However this library does.

If this library's purpose is to be a drop-in replacement, then one could argue this is a bug.

**Comment by dahlbyk** [comment]
> If this library's purpose is to be a drop-in replacement

It is!

> then one could argue this is a bug.

It is! Probably pretty easy to demo/fix, if you'd like to give it a try.

A related bug is that `disabled` inputs' values are probably included when submitted with `remote`.

**Comment by haacked** [comment]
What's an example where this comes into play for you? For example, if a field is required on the server, but disabled on the client, what do you expect to happen?

**Comment by haacked** [comment]
> * should ignore all fields within a disabled `fieldset`

I think this we get for free because the browser will disable the submit buttons and all the inputs so validation won't happen. Correct me if you have a scenario where this doesn't work.

**Comment by TanguyPa** [comment]
I have the same need as @lonix1.T his is the last feature I lack to fully migrate to this library.
