### ISSUE TITLE
Purpose of debounce

### ISSUE THREAD

**Issue by lonix1** [haacked/aspnet-client-validation#99]
I find the debounce default of 300ms to be quite slow, especially when [changing](https://github.com/haacked/aspnet-client-validation/issues/97) from validating on input to on blur.

I changed it to 0 which serves my needs, but I'm unsure why that debounce is there, and whether I'm asking for trouble by changing it.

Why is there a debounce? Am I right in assuming it's specifically for the "validate on input" scenario?

(If so, I'll write up a little section for the docs...)

**Comment by haacked** [comment]
> I changed it to 0 which serves my needs, but I'm unsure why that debounce is there, and whether I'm asking for trouble by changing it.

The primary reason for debounce is so we don't do unnecessary validation. Especially in the case of remote validation. For example, suppose someone starts typing in an input. We don't necessarily want to validate every character typed. We want to wait till there's a pause and then validate.

If 300 is too slow, I'd change it to 100 and see how that feels.
